spring.datasource.url=jdbc:postgresql://localhost:5434/unifica_erp?reWriteBatchedInserts=true&tcpKeepAlive=true&connectTimeout=10&socketTimeout=30&ApplicationName=unifica_erp
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect